apiVersion: v1
data:
  dashboard.json: ""
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"dashboard.json":""},"kind":"ConfigMap","metadata":{"annotations":{},"name":"grafana-dashboard","namespace":"cloudpulse"}}
  creationTimestamp: "2026-08-04T23:25:27Z"
  name: grafana-dashboard
  namespace: cloudpulse
  resourceVersion: "1502"
  uid: 90b3d720-9f39-41b8-b09b-c03e2d7df4ec
