services:

  postgres:
    image: postgres:16
    container_name: cloudpulse-postgres

    environment:
      POSTGRES_USER: cloudpulse
      POSTGRES_PASSWORD: cloudpulse123
      POSTGRES_DB: cloudpulse

    ports:
      - "5432:5432"

    volumes:
      - cloudpulse-postgres-data:/var/lib/postgresql/data

    restart: unless-stopped

  backend:
    build:
      context: ./backend

    container_name: cloudpulse-backend

    environment:
      DATABASE_URL: postgresql://cloudpulse:cloudpulse123@postgres:5432/cloudpulse

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    restart: unless-stopped

volumes:
  cloudpulse-postgres-data: