apiVersion: v1
kind: ConfigMap

metadata:
  name: cloudpulse-config
  namespace: cloudpulse

data:

  APP_NAME: CloudPulse

  APP_VERSION: "1.0.0"

  ENVIRONMENT: production

  DEBUG: "False"

  POSTGRES_HOST: postgres

  POSTGRES_PORT: "5432"

  POSTGRES_DB: cloudpulse

  POSTGRES_USER: cloudpulse

  PROMETHEUS_PORT: "9090"

  GRAFANA_PORT: "3000"