apiVersion: v1
kind: Secret

metadata:
  name: cloudpulse-secret
  namespace: cloudpulse

type: Opaque

stringData:

  POSTGRES_PASSWORD: cloudpulse123

  JWT_SECRET_KEY: cloudpulse-super-secret-key-change-before-production